# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c495bfb28d2a80b0f522136454a80f6072912b2f0ccfc586187b5118ee1d90fb08bc769188af10e79803de6aa589cc0432922edff2a962de94a23db230d503a1

test:
  secret_key_base: f614e3c2f7a0c1961b7ca81f4b2528bf5a6c677acf443d36252657df67efbc8bb8eaede16c7077ede9243f487a9ec82faeb68f21678080d2399bf9ffffc067a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
